### ISSUE TITLE
Batch Creation

### ISSUE THREAD

**Issue by jmawebtech** [Intacct/intacct-sdk-net-examples#5]
Hi,

Instead of creating invoices one by one, can I submit them in a batch? If so, please send me some sample code.

**Comment by jimmymcpeter** [comment]
Instead of `execute` on the client class, use the `executeBatch` function and pass a list of functions to it.

You should read up on RequestConfig in the guide here - https://developer.intacct.com/tools/sdk-net/#request-configuration
and the error handling around it here - https://developer.intacct.com/tools/sdk-net/#error-handling

The unit tests have an example here - https://github.com/Intacct/intacct-sdk-net/blob/4c0d324550d108ef22cc9a649636f3e93db2ed98/Intacct.SDK.Tests/OnlineClientTest.cs#L228
